{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clintrialx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clintrialx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clintrialx/clintrialx_{{ version }}.tar.gz
  sha256: da29affb595f3b52931d1bb1130dbe50d119c35018f863632d84f5ab6be2f0af

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-rpostgresql
    - r-dplyr
    - r-httr
    - r-lubridate
    - r-progress
    - r-readr
    - r-rmarkdown
    - r-tibble
    - r-xfun >=0.44
  run:
    - r-base
    - r-dbi
    - r-rpostgresql
    - r-dplyr
    - r-httr
    - r-lubridate
    - r-progress
    - r-readr
    - r-rmarkdown
    - r-tibble
    - r-xfun >=0.44

test:
  commands:
    - $R -e "library('clintrialx')"           # [not win]
    - "\"%R%\" -e \"library('clintrialx')\""  # [win]

about:
  home: http://www.indraneelchakraborty.com/clintrialx/
  license: Apache-2.0
  summary: Are you spending too much time fetching and managing clinical trial data? Struggling
    with complex queries and bulk data extraction? What if you could simplify this process
    with just a few lines of code? Introducing 'clintrialx' - Fetch clinical trial data
    from sources like 'ClinicalTrials.gov' <https://clinicaltrials.gov/> and the 'Clinical
    Trials Transformation Initiative - Access to Aggregate Content of ClinicalTrials.gov'
    database <https://aact.ctti-clinicaltrials.org/>, supporting pagination and bulk
    downloads. Also, you can generate HTML reports based on the data obtained from the
    sources!
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
